version: "3"
services:
  consumer: # makeit with nodejs
    build: ./consumer
    ports:
      - "3000:3000"
    environment:
      - KAFKA_HOST=kafka:9092
    volumes:
      - ./consumer:/app/
    depends_on:
      - kafka
  producer:
    build: ./go-producer
    ports:
      - "3001:3001"
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./go-producer:/app
    depends_on:
      - kafka
  zookeeper:
    image: "bitnami/zookeeper:3.8.0"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:2.8.1"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
